export const maps = (() => {
  // const testMap = [
  //   [ //floor
  //     "GGGGGGGGGGGGGGGGGGGGGGGGdddddd",
  //     "GGGGGGGGGGGGGGGGGGdGGGGGdddddd",
  //     "GdGGGwwwwwwwwwwwGGGGGGGddddddd",
  //     "GGGGGwwwwwwwwwwwGGGGGGGddddddd",
  //     "GGGGGwwwwwwwwwwwGGGGGGGGdddddd",
  //     "GGGGGwwwwwwwwwwwGGGGddGGdddddd",
  //     "GGGGGGGGGGgGGGGGGGGGGGGddddddd",
  //     "dddddGGdGGgGGGGddddddddddddddd",
  //     "ddddddddddgddddddddddddddddddd",
  //     "ddddddddddgddddddddddddddddddd",
  //     "ddddddddddgddddddddddddddddddd",
  //     "ddddddddddgddGGGdddddddddddddd",
  //     "ddddddddddgdGGGGGddddddddddddd",
  //     "ddddddddddgddGGGdddddddddddddd",
  //     "ddddddddddgggggsssssdddddddddd",
  //     "dddddddddddddddddddsdddddddddd",
  //     "dddddddddddddddddddsdddddddddd",
  //     "dddddddddddddddddddsdddddddddd",
  //     "dddddddddddddddddddsdddddddddd",
  //     "dddddddddddddddddddsdddddddddd",
  //   ],
  //   [ //walls
  //     "                              ",
  //     "                              ",
  //     "     cc+ccccc+cc              ",
  //     "     c         c              ",
  //     "     c         c              ",
  //     "     cc+cc cc+cc              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "              w               ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //   ],
  //   [ //ceiling
  //     "                              ",
  //     "                              ",
  //     "     wwwwwwwwwww              ",
  //     "     wwwwwwwwwww              ",
  //     "     wwwwwwwwwww              ",
  //     "     wwwwwwwwwww              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "            lllll             ",
  //     "           lllllll            ",
  //     "           lllllll            ",
  //     "           lllllll            ",
  //     "            lllll             ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //     "                              ",
  //   ],
  // ];
  const testMap = [
    [
     "dddGGGGGGGGGGGGGGGdddddd",
     "dGGGGGGGGGGGGGGGGGGGGddd",
     "GGGGGGGGGGGGGGGGGGGGGGdd",
     "GGGGGwwswwwwwwwwwwGGGGGG",
     "GGGGGwwwwwwwwwwwwwGGGGGG",
     "GGGGGwwwwwwwwwwwwsGGGGGG",
     "GGGGGwwwwwwwwwwwwGGGGGGG",
     "GGGGGwwwwwwwwwwwwGGGGGGG",
     "GGGGGwwwwwwwwwwwwGGGGGGG",
     "GGGGGswwwwwwwwwwwsGGGGGG",
     "GGGGGwwwwwwwwwwwwGGGGGGG",
     "GGGGGwwwGwwwwwwwwwswGGGG",
     "GGGGGwwwwwwwwwwwwwwwGGGG",
     "dGGGGwwwwwwwwwwwwwwwGGGG",
     "dGGGGwwwwwwwwwwwwwwwGGGG",
     "ddGGGsssssssssssssssGGGG",
     "ddGGGsssssssssssssssGGGG",
     "ddGGGGGGGGgggGGGGGGGGGGG",
     "ddGGGGGGGGgggGGGGGGGGGGG",
     "ddGGGGGGGGgggGGGGGGGGGGd",
     "dddGGGGGGGgggGGGGGGGGddd",
     "ddddGGGGGgggGGGGGGGddddd",
     "dddddGGGGgggGGGGGddddddd",
     "ddddddGGggggGGGGGddddddd"
    ],
    [
     "                        ",
     "                        ",
     "                        ",
     "     cc+ccccccc+cc      ",
     "     c   c  cwwwwc   w  ",
     " w   c           +      ",
     "     cww c  c    c      ",
     "     ccccc  cccccc      ",
     "     cw  c   c   c      ",
     "     +w          +      ",
     "     c   c   c   c      ",
     "     ccccc   ccccc+c    ",
     "     cww c   c ww wc    ",
     "     c            wc    ",
     "     cccccc cccccccc    ",
     "                        ",
     "                        ",
     "    w               w   ",
     "                        ",
     "                        ",
     "                        ",
     "                        ",
     "             w          ",
     "                        "
    ],
    [
     "                        ",
     "                        ",
     "ll                 llll ",
     "llll wwwwwwwwwwwwwlllll ",
     "llll wwwwwwwwwwwwwllllll",
     "llll wwwwwwwwwwwwwllllll",
     "llll wwwwwwwwwwwww   ll ",
     "lll  wwwwwwwwwwwww      ",
     "l    wwwwwwwwwwwww      ",
     "     wwwwwwwwwwwww      ",
     "     wwwwwwwwwwwww      ",
     "     wwwwwwwwwwwwwww    ",
     "     wwwwwwwwwwwwwww    ",
     "     wwwwwwwwwwwwwww l  ",
     "     wwwwwwwwwwwwwwwlll ",
     "   llll  wwwww    lllll ",
     "  lllll          lllllll",
     "  lllll          llllll ",
     "  lllll           lllll ",
     "   lll      lll   llll  ",
     "           lllll    ll  ",
     "           lllllll      ",
     "           lllllll      ",
     "            lllll       "
    ]
   ]
  return { testMap };
})();