export const maps = (() => {
  const testMap = [
    [ //floor
      "GGGGGGGGGGGGGGGGGGGGGGGGdddddd",
      "GGGGGGGGGGGGGGGGGGdGGGGGdddddd",
      "GdGGGwwwwwwwwwwwGGGGGGGddddddd",
      "GGGGGwwwwwwwwwwwGGGGGGGddddddd",
      "GGGGGwwwwwwwwwwwGGGGGGGGdddddd",
      "GGGGGwwwwwwwwwwwGGGGddGGdddddd",
      "GGGGGGGGGGgGGGGGGGGGGGGddddddd",
      "dddddGGdGGgGGGGddddddddddddddd",
      "ddddddddddgddddddddddddddddddd",
      "ddddddddddgddddddddddddddddddd",
      "ddddddddddgddddddddddddddddddd",
      "ddddddddddgddGGGdddddddddddddd",
      "ddddddddddgdGGGGGddddddddddddd",
      "ddddddddddgddGGGdddddddddddddd",
      "ddddddddddgggggsssssdddddddddd",
      "dddddddddddddddddddsdddddddddd",
      "dddddddddddddddddddsdddddddddd",
      "dddddddddddddddddddsdddddddddd",
      "dddddddddddddddddddsdddddddddd",
      "dddddddddddddddddddsdddddddddd",
    ],
    [ //walls
      "                              ",
      "                              ",
      "     cc+ccccc+cc              ",
      "     c         c              ",
      "     c         c              ",
      "     cc+cc cc+cc              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "              w               ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
    ],
    [ //ceiling
      "                              ",
      "                              ",
      "     wwwwwwwwwww              ",
      "     wwwwwwwwwww              ",
      "     wwwwwwwwwww              ",
      "     wwwwwwwwwww              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "            lllll             ",
      "           lllllll            ",
      "           lllllll            ",
      "           lllllll            ",
      "            lllll             ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
      "                              ",
    ],
  ];
  return { testMap };
})();